name: projetCV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: installation 
      run: echo 'install dependencies'

    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build website
      run: npm install && npm run build

     - name: Deploy to GitHub Pages
      uses: RCHOUATT/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: main
        FOLDER: Mon_site
