name: Déploiement de site web

on:
  push:
    branches:
      - main
  pull-request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Déploiement du site web
      uses: projetCV/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: main
        FOLDER: ./
